baseURL: "/"
languageCode: "en-us"
title: "Stanford One for the World"
# Always minify the HTML for maximum performance
minify: true
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  mounts:
  - source: ./node_modules/@fortawesome/fontawesome-free/webfonts
    target: static/sass/webfonts
  - source: ./static
    target: static
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: How to Get Involved
      url: /involved/
      weight: 2
    - name: Ambassadors
      url: /ambassadors/
      weight: 3
    - name: About Us
      url: /about/
      weight: 4
    - name: Blog
      url: /blog/
      weight: 5
    - name: Events
      url: /events/
      weight: 6