baseURL: "/"
languageCode: "en-us"
title: "One for the World @ Stanford"
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  mounts:
    - source: ./node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
    - source: ./static
      target: static
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: How to Get Involved
      url: /involved/
      weight: 2
    - name: Ambassadors
      url: /ambassadors/
      weight: 3
    - name: About Us
      url: /about/
      weight: 4
    - name: Blog
      url: /blog/
      weight: 5
    - name: Events
      url: /events/
      weight: 6
params:
  # see https://gist.github.com/jeremybise/a6afea2d4c7f9044180ffeb663a617cf
  google_fonts:
    - [Raleway]
    - [Quattrocento, "400, 700"]
    - [Pacifico]
    - [Walter Turncoat]
    - [Fira Sans]
